server:
  port: 8090
  servlet:
    context-path: /glofox

spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  datasource:
    url: jdbc:h2:file:./glofox-h2-db
    username: glofox
    password:
    driver-class-name: org.h2.Driver


